sudo: false
language: node_js
node_js:
  - 7
  - 6

matrix:
  include:
    - node_js: 5
      env: TEST_PATH="test/test.js test/test-post*.js"
    - node_js: 4
      env: TEST_PATH="test/test.js test/test-post*.js"

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

script: npm test $TEST_PATH
