environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
      environment: TEST_PATH=test/test.js test/test-post*.js
    - nodejs_version: "4"
      environment: TEST_PATH=test/test.js test/test-post*.js

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install

test_script:
  - node --version && npm --version
  - cmd: echo %TEST_PATH%
  - cmd: npm test %TEST_PATH%
